//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 02:50:11 AM EET 
//


package com.ibm.finance.palink.common.dto.dashboard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}customerName"/>
 *         &lt;element ref="{}IBMCustomerNumber"/>
 *         &lt;element ref="{}IBM_DOMSTC_BUYG_GRP_CLNT_NAME"/>
 *         &lt;element ref="{}IBM_DOMSTC_BUYG_GRP_CLNT_NUM"/>
 *         &lt;element ref="{}DOM_CLIENT_ID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerName",
    "ibmCustomerNumber",
    "ibmDomstcBuyGrpClntName",
    "ibmDomstcBuyGrpClntNum",
    "domClientId"
})
@XmlRootElement(name = "CustomerInformation")
public class CustomerInformationDto {

    @XmlElement(required = true)
    protected String customerName;
    @XmlElement(name = "IBMCustomerNumber", required = true)
    protected String ibmCustomerNumber;
    @XmlElement(name = "IBM_DOMSTC_BUYG_GRP_CLNT_NAME", required = true)
    protected String ibmDomstcBuyGrpClntName;
    @XmlElement(name = "IBM_DOMSTC_BUYG_GRP_CLNT_NUM", required = true)
    protected String ibmDomstcBuyGrpClntNum;
    @XmlElement(name = "DOM_CLIENT_ID", required = true)
    protected String domClientId;

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }


	public String getIbmCustomerNumber() {
		return ibmCustomerNumber;
	}

	public void setIbmCustomerNumber(String ibmCustomerNumber) {
		this.ibmCustomerNumber = ibmCustomerNumber;
	}

	public String getIbmDomstcBuyGrpClntName() {
		return ibmDomstcBuyGrpClntName;
	}

	public void setIbmDomstcBuyGrpClntName(String ibmDomstcBuyGrpClntName) {
		this.ibmDomstcBuyGrpClntName = ibmDomstcBuyGrpClntName;
	}

	public String getIbmDomstcBuyGrpClntNum() {
		return ibmDomstcBuyGrpClntNum;
	}

	public void setIbmDomstcBuyGrpClntNum(String ibmDomstcBuyGrpClntNum) {
		this.ibmDomstcBuyGrpClntNum = ibmDomstcBuyGrpClntNum;
	}

	public String getDomClientId() {
		return domClientId;
	}

	public void setDomClientId(String domClientId) {
		this.domClientId = domClientId;
	}

}
