//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 02:50:11 AM EET 
//


package com.ibm.finance.palink.common.dto.dashboard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ResponseHeader"/>
 *         &lt;element ref="{}QuoteInformation"/>
 *         &lt;element ref="{}HistoricalData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "quoteInformation",
    "historicalData"
})
@XmlRootElement(name = "DashboardResponse")
public class DashboardResponseDto {

    @XmlElement(name = "ResponseHeader", required = true)
    protected ResponseHeaderDto responseHeader;
    @XmlElement(name = "QuoteInformation", required = true)
    protected QuoteInformationDto quoteInformation = new QuoteInformationDto();
    @XmlElement(name = "HistoricalData", required = true)
    protected HistoricalDataDto historicalData = new HistoricalDataDto();

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseHeaderDto }
     *     
     */
    public ResponseHeaderDto getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseHeaderDto }
     *     
     */
    public void setResponseHeader(ResponseHeaderDto value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the quoteInformation property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInformationDto }
     *     
     */
    public QuoteInformationDto getQuoteInformation() {
        return quoteInformation;
    }

    /**
     * Sets the value of the quoteInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInformationDto }
     *     
     */
    public void setQuoteInformation(QuoteInformationDto value) {
        this.quoteInformation = value;
    }

    /**
     * Gets the value of the historicalData property.
     * 
     * @return
     *     possible object is
     *     {@link HistoricalDataDto }
     *     
     */
    public HistoricalDataDto getHistoricalData() {
        return historicalData;
    }

    /**
     * Sets the value of the historicalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoricalDataDto }
     *     
     */
    public void setHistoricalData(HistoricalDataDto value) {
        this.historicalData = value;
    }

}
