//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 02:50:11 AM EET 
//


package com.ibm.finance.palink.common.dto.dashboard;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HistoricalQuoteID"/>
 *         &lt;element ref="{}QuoteType"/>
 *         &lt;element ref="{}WEB_QUOTE_NUM"/>
 *         &lt;element ref="{}QuoteID"/>
 *         &lt;element ref="{}Part_NUM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SUM_ENTITLED"/>
 *         &lt;element ref="{}SUM_QUOTED"/>
 *         &lt;element ref="{}System_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Product_brand" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SUM_List"/>
 *         &lt;element ref="{}DealSize"/>
 *         &lt;element ref="{}Discount"/>
 *         &lt;element ref="{}APPROVAL_DATE"/>
 *         &lt;element ref="{}quote_date"/>
 *         &lt;element ref="{}SW_PROD_BRAND_CODE_DSCR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}WW_PROD_SET_DSCR"/>
 *         &lt;element ref="{}cmrsectorname"/>
 *         &lt;element ref="{}cmrisuname"/>
 *         &lt;element ref="{}dom_buy_grp_id"/>
 *         &lt;element ref="{}Value_seller"/>
 *         &lt;element ref="{}CNTRY_CODE"/>
 *         &lt;element ref="{}Web_Quote_Currency_Code"/>
 *         &lt;element ref="{}CountryCode"/>
 *         &lt;element ref="{}Currency_Code"/>
 *         &lt;element ref="{}WIN"/>
 *         &lt;element ref="{}WinLoss"/>
 *         &lt;element ref="{}UpgMES"/>
 *         &lt;element ref="{}IBM_DOMSTC_BUYG_GRP_CLNT_NAME"/>
 *         &lt;element ref="{}FULFILLMENT"/>
 *         &lt;element ref="{}dom_buy_grp_name"/>
 *         &lt;element ref="{}Indirect"/>
 *         &lt;element ref="{}OpportunityID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "historicalQuoteId","quoteType","quoteId","sysType", "webQuoteNum",
		"partNum","productBrand", "sumEntitled", "sumList", "sumQuoted", "dealSize", "discount", "submitDate", "quoteDate",
		"swProdBrandCodeDscr", "wwProdSetDscr", "cmrSectorName", "cmrIsUname", "cntryCode", "domBuyGrpId",
		"valueSeller", "countryCode", "currencyCode","webQuoteCurrencyCode", "win", "winLoss", "ibmDomstcBuyGrpClntName",
		"fulfillment", "upgMes", "domBuyGrpName", "indirect", "opportunityId" })

@XmlRootElement(name = "HistoricalQuote")
public class HistoricalQuoteDto {

    @XmlElement(name = "HistoricalQuoteID")
    protected Integer historicalQuoteId;
    @XmlElement(name = "QuoteType")
    protected String quoteType;
    @XmlElement(name = "WEB_QUOTE_NUM")
    protected Integer webQuoteNum;
    @XmlElement(name = "Part_NUM")
    protected List<String> partNum;
    @XmlElement(name = "SUM_ENTITLED")
    protected Float sumEntitled;
    @XmlElement(name = "SUM_QUOTED")
    protected Float sumQuoted;
    @XmlElement(name = "Discount")
    protected Float discount;
    @XmlElement(name = "SUBMIT_DATE", required = true)
    protected String submitDate;
    @XmlElement(name = "SW_PROD_BRAND_CODE_DSCR", required = true)
    protected List<String> swProdBrandCodeDscr;
    @XmlElement(name = "WW_PROD_SET_DSCR", required = true)
    protected List<String>  wwProdSetDscr;
    @XmlElement(name = "CNTRY_CODE", required = true)
    protected String cntryCode;
    @XmlElement(name = "Web_Quote_Currency_Code", required = true)
    protected String webQuoteCurrencyCode;
    @XmlElement(name = "WIN")
    protected String win;
    @XmlElement(name = "IBM_DOMSTC_BUYG_GRP_CLNT_NAME", required = true)
    protected String ibmDomstcBuyGrpClntName;
    @XmlElement(name = "FULFILLMENT", required = true)
    protected String fulfillment;
    @XmlElement(name = "OpportunityID", required = true)
    protected String opportunityId;
    
    /** HW historical data fields start */
    @XmlElement(name = "QuoteID", required = true)
    protected String quoteId;
    @XmlElement(name = "System_type", required = true)
    protected List<String> sysType;
    @XmlElement(name = "Product_brand", required = true)
    protected List<String> productBrand;
    @XmlElement(name = "SUM_List")
    protected Float sumList;
    @XmlElement(name = "DealSize")
    protected Float dealSize;
    @XmlElement(name = "quote_date", required = true)
    protected String quoteDate;
    @XmlElement(name = "cmrsectorname", required = true)
    protected String cmrSectorName;
    @XmlElement(name = "cmrisuname")
    protected String cmrIsUname;
    @XmlElement(name = "dom_buy_grp_id", required = true)
    protected String domBuyGrpId;
    @XmlElement(name = "Value_seller")
    protected Integer valueSeller;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "Currency_Code", required = true)
    protected String currencyCode;
    @XmlElement(name = "WinLoss")
    protected String winLoss;
    @XmlElement(name = "UpgMES")
    protected String upgMes;
    @XmlElement(name = "dom_buy_grp_name", required = true)
    protected String domBuyGrpName;
    @XmlElement(name = "Indirect")
    protected Integer indirect;

       /**
     * Gets the value of the discount property.
     * 
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(Float value) {
        this.discount = value;
    }

    public String getSubmitDate() {
		return submitDate;
	}

	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}

	/**
     * Gets the value of the webQuoteCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebQuoteCurrencyCode() {
        return webQuoteCurrencyCode;
    }

    /**
     * Sets the value of the webQuoteCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebQuoteCurrencyCode(String value) {
        this.webQuoteCurrencyCode = value;
    }


	public Integer getHistoricalQuoteId() {
		return historicalQuoteId;
	}

	public void setHistoricalQuoteId(Integer historicalQuoteId) {
		this.historicalQuoteId = historicalQuoteId;
	}

	public Integer getWebQuoteNum() {
		return webQuoteNum;
	}

	public void setWebQuoteNum(Integer webQuoteNum) {
		this.webQuoteNum = webQuoteNum;
	}

	public List<String> getPartNum() {
		return partNum;
	}

	public void setPartNum(List<String> partNum) {
		this.partNum = partNum;
	}

	public Float getSumEntitled() {
		return sumEntitled;
	}

	public void setSumEntitled(Float sumEntitled) {
		this.sumEntitled = sumEntitled;
	}

	public Float getSumQuoted() {
		return sumQuoted;
	}

	public void setSumQuoted(Float sumQuoted) {
		this.sumQuoted = sumQuoted;
	}

	public List<String> getSwProdBrandCodeDscr() {
		return swProdBrandCodeDscr;
	}

	public void setSwProdBrandCodeDscr(List<String> swProdBrandCodeDscr) {
		this.swProdBrandCodeDscr = swProdBrandCodeDscr;
	}

	public List<String> getWwProdSetDscr() {
		return wwProdSetDscr;
	}

	public void setWwProdSetDscr(List<String> wwProdSetDscr) {
		this.wwProdSetDscr = wwProdSetDscr;
	}

	public String getCntryCode() {
		return cntryCode;
	}

	public void setCntryCode(String cntryCode) {
		this.cntryCode = cntryCode;
	}

	public String getWin() {
		return win;
	}

	public void setWin(String win) {
		this.win = win;
	}

	public String getIbmDomstcBuyGrpClntName() {
		return ibmDomstcBuyGrpClntName;
	}

	public void setIbmDomstcBuyGrpClntName(String ibmDomstcBuyGrpClntName) {
		this.ibmDomstcBuyGrpClntName = ibmDomstcBuyGrpClntName;
	}

	public String getFulfillment() {
		return fulfillment;
	}

	public void setFulfillment(String fulfillment) {
		this.fulfillment = fulfillment;
	}

	public String getOpportunityId() {
		return opportunityId;
	}

	public void setOpportunityId(String opportunityId) {
		this.opportunityId = opportunityId;
	}

	/**
	 * @return the quoteType
	 */
	public String getQuoteType() {
		return quoteType;
	}

	/**
	 * @param quoteType the quoteType to set
	 */
	public void setQuoteType(String quoteType) {
		this.quoteType = quoteType;
	}

	/**
	 * @return the quoteId
	 */
	public String getQuoteId() {
		return quoteId;
	}

	/**
	 * @param quoteId the quoteId to set
	 */
	public void setQuoteId(String quoteId) {
		this.quoteId = quoteId;
	}

	/**
	 * @return the sysType
	 */
	public List<String> getSysType() {
		return sysType;
	}

	/**
	 * @param sysType the sysType to set
	 */
	public void setSysType(List<String> sysType) {
		this.sysType = sysType;
	}

	/**
	 * @return the productBrand
	 */
	public List<String> getProductBrand() {
		return productBrand;
	}

	/**
	 * @param productBrand the productBrand to set
	 */
	public void setProductBrand(List<String> productBrand) {
		this.productBrand = productBrand;
	}

	/**
	 * @return the sumList
	 */
	public Float getSumList() {
		return sumList;
	}

	/**
	 * @param sumList the sumList to set
	 */
	public void setSumList(Float sumList) {
		this.sumList = sumList;
	}

	/**
	 * @return the dealSize
	 */
	public Float getDealSize() {
		return dealSize;
	}

	/**
	 * @param dealSize the dealSize to set
	 */
	public void setDealSize(Float dealSize) {
		this.dealSize = dealSize;
	}

	/**
	 * @return the quoteDate
	 */
	public String getQuoteDate() {
		return quoteDate;
	}

	/**
	 * @param quoteDate the quoteDate to set
	 */
	public void setQuoteDate(String quoteDate) {
		this.quoteDate = quoteDate;
	}

	/**
	 * @return the cmrSectorName
	 */
	public String getCmrSectorName() {
		return cmrSectorName;
	}

	/**
	 * @param cmrSectorName the cmrSectorName to set
	 */
	public void setCmrSectorName(String cmrSectorName) {
		this.cmrSectorName = cmrSectorName;
	}

	/**
	 * @return the cmrIsUname
	 */
	public String getCmrIsUname() {
		return cmrIsUname;
	}

	/**
	 * @param cmrIsUname the cmrIsUname to set
	 */
	public void setCmrIsUname(String cmrIsUname) {
		this.cmrIsUname = cmrIsUname;
	}

	/**
	 * @return the domBuyGrpId
	 */
	public String getDomBuyGrpId() {
		return domBuyGrpId;
	}

	/**
	 * @param domBuyGrpId the domBuyGrpId to set
	 */
	public void setDomBuyGrpId(String domBuyGrpId) {
		this.domBuyGrpId = domBuyGrpId;
	}

	/**
	 * @return the valueSeller
	 */
	public Integer getValueSeller() {
		return valueSeller;
	}

	/**
	 * @param valueSeller the valueSeller to set
	 */
	public void setValueSeller(Integer valueSeller) {
		this.valueSeller = valueSeller;
	}

	/**
	 * @return the countryCode
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * @param countryCode the countryCode to set
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**
	 * @return the currencyCode
	 */
	public String getCurrencyCode() {
		return currencyCode;
	}

	/**
	 * @param currencyCode the currencyCode to set
	 */
	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	/**
	 * @return the winLoss
	 */
	public String getWinLoss() {
		return winLoss;
	}

	/**
	 * @param winLoss the winLoss to set
	 */
	public void setWinLoss(String winLoss) {
		this.winLoss = winLoss;
	}

	/**
	 * @return the upgMes
	 */
	public String getUpgMes() {
		return upgMes;
	}

	/**
	 * @param upgMes the upgMes to set
	 */
	public void setUpgMes(String upgMes) {
		this.upgMes = upgMes;
	}

	/**
	 * @return the domBuyGrpName
	 */
	public String getDomBuyGrpName() {
		return domBuyGrpName;
	}

	/**
	 * @param domBuyGrpName the domBuyGrpName to set
	 */
	public void setDomBuyGrpName(String domBuyGrpName) {
		this.domBuyGrpName = domBuyGrpName;
	}

	/**
	 * @return the indirect
	 */
	public Integer getIndirect() {
		return indirect;
	}

	/**
	 * @param indirect the indirect to set
	 */
	public void setIndirect(Integer indirect) {
		this.indirect = indirect;
	}

}
