//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 02:50:11 AM EET 
//


package com.ibm.finance.palink.common.dto.dashboard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LEADING_BRAND"/>
 *         &lt;element ref="{}Web_Quote_Currency_Code"/>
 *         &lt;element ref="{}SSWQuote"/>
 *         &lt;element ref="{}SaaSQuote"/>
 *         &lt;element ref="{}CustomerInformation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "leadingBrand",
    "webQuoteCurrencyCode",
    "customerInformation"
})
@XmlRootElement(name = "QuoteInformation")
public class QuoteInformationDto {

    @XmlElement(name = "LEADING_BRAND", required = true)
    protected String leadingBrand;
    @XmlElement(name = "Web_Quote_Currency_Code", required = true)
    protected String webQuoteCurrencyCode;
    @XmlElement(name = "CustomerInformation", required = true)
    protected CustomerInformationDto customerInformation;

    public String getLeadingBrand() {
		return leadingBrand;
	}

	public void setLeadingBrand(String leadingBrand) {
		this.leadingBrand = leadingBrand;
	}

	/**
     * Gets the value of the webQuoteCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebQuoteCurrencyCode() {
        return webQuoteCurrencyCode;
    }

    /**
     * Sets the value of the webQuoteCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebQuoteCurrencyCode(String value) {
        this.webQuoteCurrencyCode = value;
    }

    /**
     * Gets the value of the customerInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInformationDto }
     *     
     */
    public CustomerInformationDto getCustomerInformation() {
        return customerInformation;
    }

    /**
     * Sets the value of the customerInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInformationDto }
     *     
     */
    public void setCustomerInformation(CustomerInformationDto value) {
        this.customerInformation = value;
    }

}
